### ISSUE TITLE
Majeure : Clôture de caisse - Mise en coffre

### ISSUE THREAD

**Issue by Mounia-kazi** [algerowalid/POS_v1.0#102]
Dounia 

J'ai ouvert la caisse en mettant une valeur de 10000, puis sans réaliser de vente j'ai clôturé la caisse. J'ai passé l'étape 1, j'ai mis 0 dans les champs puis je suis passée à l'étape 2, en essayant de mettre une valeur dans la mise en coffre l'application a planté.** -->Problème 1**

Puis je me suis connectée de nouveau. Normalement étant donnée que je n'ai pas validé la clôture de la caisse puis ça a planté avant je dois avoir une caisse ouverte hors la caisse est fermé --> **Problème 2**. 

Attention : tant que les opérations au niveau d'un parcours ne sont pas valider (action finale du parcours) alors les informations ne doivent pas être enregistrées en base de données, elles doivent juste être stockées dans la session de l'utilisateur.

**Comment by marwabekrar** [comment]
J'arrive pas à reproduire ce problème, ça plante pas pour moi

**Comment by Dounia-kazi** [comment]
non reproductible
