### ISSUE TITLE
Majeure : Clôture de caisse - Mise en coffre - Montant compté

### ISSUE THREAD

**Issue by Mounia-kazi** [algerowalid/POS_v1.0#103]
Dounia

Pré-requis : Je n'ai pas réalisé de vente

Je clôture ma caisse et je remplis tous les champs : espèces, chèques,...etc.

Résultat 1 : quand j'ai cliqué sur suivant dans comptage, ça a planté

Résultat 2 : j'ai voulu reproduire le problème, je refais la même opération, cette fois-ci ça ne plante pas mais ça m'affiche dans la colonne Montant compté des valeurs à 0 sur les champs chèques, carte bancaire et chèque restaurant.

**Comment by marwabekrar** [comment]
corrigé
