### ISSUE TITLE
Majeure : Ecran vente, encaissement et ticket : Prix HT affiché est incorrect

### ISSUE THREAD

**Issue by Mounia-kazi** [algerowalid/POS_v1.0#118]
J'ai un produit avec le prix suivante 

prix HT : 1200
Prix TTC : 1404
code TVA 17
c'est un prix promotionnel

lorsque je sélectionne ce produit il m'affiche le prix HT de 1165
TVA : 238
et le montant TTC de 1404, y a que le montant TTC qui est correct.

Problème apparaît également au niveau du ticket.

**Comment by Dounia-kazi** [comment]
Test OK
