### ISSUE TITLE
Majeure : Ecran ventre : liste produits : manque certaines informations

### ISSUE THREAD

**Issue by Dounia-kazi** [algerowalid/POS_v1.0#124]
ce que j'avais marqué dans le conception : 

<désignation> - référence
<libellé du prix> <prix TTC unitaire><devise> / <mesure>

Il manque : 
Le libellé de prix -> affiche si la valeur est renseignée
la mesure n'est pas affichée

le prix TTC apparaît deux fois hors il doit apparaître une seule fois sur la ligne

**Comment by algerowalid** [comment]
- référence:  j'ai fait le test, le ticket va être encombrant, les références des produits sont parfois une longue chaines de caractère.
- idem pour le prix, par contre j'ai ajouter un toast qui indique si le produit est en promotion ou non.
- si vous confirmer la nécessité d'afficher les deux informations je l'appliquerai le dimanche. 
 
- le prix TTC  n’apparaît pas 2 fois, c'est le prix TTC  unitaire et le prix TTC  total de produit, si tu changes la quantité de produit tu le remarquera.
