### ISSUE TITLE
Majeur : ajout produit sur une commande

### ISSUE THREAD

**Issue by Dounia-kazi** [algerowalid/POS_v1.0#133]
Majeure : la dates, statut et mode de paiement ne sont pas obligatoire pour l'ajout d'un produit sur une commande.

**Comment by marwabekrar** [comment]
corrigé

**Comment by Mounia-kazi** [comment]
En créant une commande l'application bug au moment ou je clique sur "sauvegarder"

**Comment by marwabekrar** [comment]
Walid a désinstallé l'ancienne version sur ton Citaq?

**Comment by Mounia-kazi** [comment]
tu veux dire installé ? oui j'ai la dernière version.

**Comment by marwabekrar** [comment]
ça  bug pas chez moi, j'arrive pas à avoir ce problème
