### ISSUE TITLE
Majeure : Création de la commande

### ISSUE THREAD

**Issue by Dounia-kazi** [algerowalid/POS_v1.0#145]
Ecran création de commande
Le bouton SAUVEGARDER n’a pas la même police que le bouton Annuler.
Les libellés des en-têtes ne doivent pas être en gras
Fautes d’orthographe : réception, échéance

**Comment by Mounia-kazi** [comment]
Walid a corrigé le bouton sauvegarder ainsi que les en-têtes mais il ne peut pas corriger les fautes d'orthographe des boutons de dates.

**Comment by marwabekrar** [comment]
je vais regler ça

**Comment by marwabekrar** [comment]
réglé

**Comment by Mounia-kazi** [comment]
peux tu corriger également les libellé du statut "Réceptionnée, annulée..."

**Comment by marwabekrar** [comment]
oui

**Comment by Mounia-kazi** [comment]
ok

**Comment by Dounia-kazi** [comment]
mettre la valeur : En cours comme valeur par défaut pour le statut de la commande
Ajouter la valeur Virement dans la liste mode de paiement
