### ISSUE TITLE
Majeure : Utilisation de la notion de Liste de valeurs KO - Statut commande

### ISSUE THREAD

**Issue by Dounia-kazi** [algerowalid/POS_v1.0#146]
Statut commande 

Ce que l'on stock dans la table commande est la valeur code de la liste de valeur STATUT_COMMANDE 

hors je vois la même valeur dans le champ code de la liste de valeurs.

Idem pour les autres listes de valeurs.

**Comment by marwabekrar** [comment]
corrigé
