### ISSUE TITLE
Majeure : Ticket de caisse : problème affichage des décimales

### ISSUE THREAD

**Issue by Dounia-kazi** [algerowalid/POS_v1.0#151]
Les valeurs sur chaque lignes doivent s'afficher sur deux décimales
Prix HT, taxe sur deux décimales également

rendu et mode d'encaissement également sur deux décimale. 

Il y a un souci sur le champ versement, il y a deux points au lieu d'un seul.

Il faut choisir entre le point et la virgule pour la décimale, je choisis le point.

**Comment by algerowalid** [comment]
Réglé
