### ISSUE TITLE
L'exportation en Excel ne marche pas.

### ISSUE THREAD

**Issue by Mounia-kazi** [algerowalid/POS_v1.0#21]

**Comment by marwabekrar** [comment]
A mon niveau, je ne peux pas exécuter ce code , ça marche pas sur l'emulateur. il faut voir avec walid ou achref pour voir pourquoi ça marche pas

**Comment by marwabekrar** [comment]
Dupliqué

**Comment by Mounia-kazi** [comment]
non l'autre c'était pour le message d'erreur que tu as corrigé
