### ISSUE TITLE
Clôture caisse

### ISSUE THREAD

**Issue by Mounia-kazi** [algerowalid/POS_v1.0#24]
Le calculs de la somme des ventes sur l'interface de la mise en coffre est faux.

**Comment by marwabekrar** [comment]
L'erreur a été corrigé par Walid. C'était une erreur causée par une fausse insertion de l'ID caisse lors de l'encaissement.

**Comment by Mounia-kazi** [comment]
Ok, je verrai ça quand je referais les tests. On refait toujours les tests et plusieurs fois.
