### ISSUE TITLE
Fenêtre ouverture caisse

### ISSUE THREAD

**Issue by Mounia-kazi** [algerowalid/POS_v1.0#30]
Le bouton qui ferme la fenêtre "Ouverture caisse" ne marche pas et en cliquant sur le bouton "continuer sans ouvrir la caisse" l'application s'arrête.

**Comment by marwabekrar** [comment]
Le deuxième problème est réglé.  Pour le bouton "fermer" , c'est un problème de découpage de l'interface. ça nécessite l'intervention de Lahcene aussi.
