### ISSUE TITLE
Journal caisse

### ISSUE THREAD

**Issue by Mounia-kazi** [algerowalid/POS_v1.0#42]
Corriger "Journal caisse" (enlever "de la")
L'écriture de sur cette fenêtre est trop petite et avec une couleur illisible ; changer le gris.

**Comment by marwabekrar** [comment]
Pour les problèmes de design (taille des fenetres , tableau, textes ... etc), je dois attendre l'intervention de Lahcene. Je te ferai signe quand j'intègre les nouvelles interfaces.

**Comment by Mounia-kazi** [comment]
Ok.

**Comment by Mounia-kazi** [comment]
Ok.

**Comment by Mounia-kazi** [comment]
Quand je clique sur une "information caisse" pour pouvoir sortir le journal de caisse l'application bug.

**Comment by marwabekrar** [comment]
C'est pas réglé?

**Comment by Mounia-kazi** [comment]
Non ça bug toujours je viens d'essayer.

**Comment by marwabekrar** [comment]
Peux tu stp me dire l'erreur qu'il t'affiche, car  sur ma machine, j'ai pas ce problème.

**Comment by Mounia-kazi** [comment]
"l'application POS s'est arrêtée"
