### ISSUE TITLE
Historique caisse (tableau) 2

### ISSUE THREAD

**Issue by Mounia-kazi** [algerowalid/POS_v1.0#9]
Régler le décalage dans le tableau entre les informations et les titres et rétrécir la taille de l'heure pas rapport à celle de la date

**Comment by Mounia-kazi** [comment]
Le problème du décalage est réglé, il reste le problème de la taille de l'heure.

**Comment by marwabekrar** [comment]
d'accord, je vais voir ça

**Comment by marwabekrar** [comment]
c'est  réglé, non ?

**Comment by Mounia-kazi** [comment]
La taille de l'heure est toujours de la même taille que la date.
